name: Build Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    name: Build ${{ matrix.os }} ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        arch: [x64, arm64]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          architecture: ${{ matrix.arch }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build with py2app
        run: |
          python setup.py py2app

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: audio-switcher-macos-${{ matrix.arch }}
          path: dist/Audio Switcher.app

  create_release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v3
        
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            audio-switcher-macos-x64/Audio Switcher.app
            audio-switcher-macos-arm64/Audio Switcher.app
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
